language: php

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - '7.1'
  - '7.2'

matrix:
  fast_finish: true
  include:
    - php: '7.1'
      env: SYMFONY_VERSION='~3.4.*'
    - php: '7.2'
      env: SYMFONY_VERSION='~3.4.*'
    - php: 'nightly'
      env:
        - COMPOSER_FLAGS='--ignore-platform-reqs'
        - SYMFONY_DEPRECATIONS_HELPER='weak'
        - SYMFONY_VERSION='~3.4.*'
  allow_failures:
    - php: 'nightly'
    - env: SYMFONY_VERSION='~3.4.*'

install:
  - phpenv config-rm xdebug.ini || true
  - if [ "$SYMFONY_VERSION" != "" ]; then
        composer require --no-update "symfony/symfony:${SYMFONY_VERSION}";
    fi
  - composer update --prefer-dist --no-suggest $COMPOSER_FLAGS

script: vendor/bin/phpunit --verbose

notifications:
  email: false
